auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: jacklybill's zone
url: http://jacklybill.github.io
feed: /atom.xml
author_info: <a href="http://jacklybill.github.io/">jacklybill</a>
